### ISSUE TITLE
[Enhancement Item] All linters' configurations can be integrated into `setup.cfg`

### ISSUE THREAD

**Issue by Curt-Park** [dongminlee94/meta-learning-for-everyone#106]
## Is your feature request related to a problem? Please describe.
All linters' configurations can be integrated into `setup.cfg`.

## Describe the solution you'd like
https://github.com/annotation-ai/python-project-template/blob/main/setup.cfg
You can see the integrated configurations for `black`, `isort`, `mypy`, `flake8`, `pylint`, `pytest`.

**Comment by dongminlee94** [comment]
@Curt-Park Done. Thank you~!
