### ISSUE TITLE
Colab에서 torchmeta import 문제

### ISSUE THREAD

**Issue by Ssojux2** [dongminlee94/meta-learning-for-everyone#116]
현재 Colab에서 해당 코드 실행시 torchmeta가 import가 안되는 문제가 발생합니다.

파이썬 버전 문제인가 싶어서 python3.7로 실행했는데,
패키지 설치까진되고, 따로 import가 안됩니다.

혹시 해결하신분 계신가요?

```
Installing collected packages: urllib3, typing-extensions, tqdm, Pillow, ordered-set, numpy, idna, charset-normalizer, certifi, torch, requests, h5py, torchvision, torchmeta
Successfully installed Pillow-9.5.0 certifi-2022.12.7 charset-normalizer-3.1.0 h5py-3.8.0 idna-3.4 numpy-1.21.6 ordered-set-4.1.0 requests-2.30.0 torch-1.9.1 torchmeta-1.8.0 torchvision-0.10.1 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-2.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

<img width="718" alt="image" src="https://user-images.githubusercontent.com/9550691/236655297-b5b294cd-09de-4791-ac62-bd94fda0fb20.png">

**Comment by Ssojux2** [comment]
@junlee94 저때 colab에서 이전 런타임으로 변경해서 진행했었는데, 패키지 버전 문제였던 것으로 기억합니다.

**Comment by junlee94** [comment]
에러코드 따라 나오는 버전들 중 아무거나 하나씩 선택해서 하셨나요? 책에 나와있는 버전과 가장 비슷한 숫자로 골랐는데도 안되서요ㅜ

**Comment by Ssojux2** [comment]
@junlee94 그때 이것저것 다 낮추면서 테스트를 진행했어서 정확히 버전은 기억이 안나는데, 파이썬 버전 낮추고 다른 패키지들 까지 같이 낮췄던 것으로 기억합니다.

**Comment by dongminlee94** [comment]
#117 에서 해당 이슈 같이 다루겠습니다. 해결 방법 적어두었습니다.
