### ISSUE TITLE
About Productivity

### ISSUE THREAD

**Issue by PeppaCat** [dongminlee94/meta-learning-for-everyone#69]
Hi, friends. I happen to find this great repo! It seems much elegant than most other meta-rl implementations. I wonder if the `Feature` branch is tested on environments like `cheetah` and can be readily used for other environments. Thanks!

**Comment by dongminlee94** [comment]
Hello, @PeppaCat. Sorry for the late response. 
As you said, you can test this code in other environments enough!

**Comment by PeppaCat** [comment]
Thanks, I am working on it!
